site_name: Owl Framework Docs
theme: yeti
repo_url: https://github.com/owl-framework/docs/
site_author: Dmitry Patsura @ovr
copyright: Owl Team and Contributors
pages:
  - [index.md, Home]
  - [cache.md, Cache]
  - [filter.md, Filter]
  - [dbal.md, Database Abstract Layer]
  - [di.md, Dependency injection]
  - [http.md, HTTP Layer]
